### ISSUE TITLE
API (GetDetails) Doen't Work on ASP.NET website

### ISSUE THREAD

**Issue by triunitytransformations** [ipinfo/csharp#13]
The following error is generated in ASP.NET v.4.8 web page calling IPinfo v.2.0.2 API synchronously:
Failed to send message to browser link server:
Error: SignalR: Connection must be started before data can be sent. Call .start() before .send()
The thread 0xd8ec has exited with code 0 (0x0).
Exception thrown: 'System.IO.FileLoadException' in IPinfo.dll
// followed by ...
Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
The same code works fine in a Winforms .NET 4.8 Framework environment, with identical .nuget library references. 
Cleaned out ASP.NET temporary files beforehand.  Cleaned out extraneous .nuget library packages.
Entire ASP.NET solution is available upon request, but it is HUGE.
The attached Function is called in response to a button_click event on an ASP.NET web page.  The button resides within an AjaxPanel webform control.
[GetClientIpValue.zip](https://github.com/ipinfo/csharp/files/9638918/GetClientIpValue.zip)

**Comment by UmanShahzad** [comment]
@SobanMahmood can we check why this works in .NET 4.8 Framework just fine but not ASP.NET 4.8?

**Comment by SobanMahmood** [comment]
@triunitytransformations 
We are supporting compatibility only for the versions which are officially being supported by Microsoft. The .NET v4.8 is not being supported anymore by Microsoft.
One thing that can be tried is to upgrade the version above ASP.NET v5 for your application. That should work hopefully.

**Comment by UmanShahzad** [comment]
I guess this needs the latest version of ASP.NET Core or something.

Let us know if it doesn't work even with that change.
