### ISSUE TITLE
GetDetailsAsync should have overload that takes IPAddress

### ISSUE THREAD

**Issue by Daniel15** [ipinfo/csharp#5]
The `IPAddress` class is the correct one to represent an IP address, and should be preferred over using a `string`. https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress

Can you please add an override for `GetDetailsAsync` in `IPApi` that takes an `IPAddress` instead of a `string`? You can call `ip.ToString()` to get a string representation of the IP, and then pass that to the current `string`-accepting method.

**Comment by SobanMahmood** [comment]
Thanks for your suggestion. That indeed will be useful to have such overridden method. We will get to it soon.

**Comment by UmanShahzad** [comment]
Solved in #12 - we'll release soon.
